### ISSUE TITLE
using uuids as object_id

### ISSUE THREAD

**Issue by anfinger** [joshmaker/django-admin-locking#1]
I am using uuids as object_ids in my model. I changed regex in urls.py/admin.py and altered object_id in models.py but it still does not work. there are no tuples in locking table in the database. what can i do that django-admin-locking works with uuids?

**Comment by joshmaker** [comment]
@anfinger, without knowing the error message you are seeing I'm not sure I can diagnose the problem, however the issue might be with `id` column on the `Lock` model which takes the form of `self.id = "%s.%s" % (self.content_type_id, self.object_id)` (take a look at the `save` method).

It's also possible that something in the JavaScript expects the `object_id` to be an integer, so you might want to look there as well. Good luck!
