### ISSUE TITLE
Change /locking to /__locking__

### ISSUE THREAD

**Issue by bowbahdoe** [joshmaker/django-admin-locking#4]
/locking can interfere with existing url schemes. In my head it seems like it would be safer to use \_\_locking\_\_ like django debug toolbar uses \_\_debug\_\_ for its routes

**Comment by unmade** [comment]
@bowbahdoe 
You could include it in your urls.py as you liked it, for example

```python
url(r'^__locking__/', include('locking.urls')),
```

**Comment by joshmaker** [comment]
Yes, the `url(r'^locking/', include('locking.urls')),` is customizable, you can use whatever namespace is safe for your project. (However, if changing the root URL from that suggested in the readme isn't working, please open a bug for that issue).
